### ISSUE TITLE
Patch to upstream v3.1

### ISSUE THREAD

**Issue by cavaliercoder** [cavaliercoder/dmidecode-osx#4]
dmidecode v3.1 was recently released and should be merged down.

**Comment by chicagotripp** [comment]
What is the best way to go about this? git merge, git rebase, git rebase and then git merge the rebase and master, or git revert?

**Comment by cavaliercoder** [comment]
I'm not sure the best plan. My working plan was to:
- create a v3.0 branch at the current HEAD
- rebase master onto the upstream
- fix any code issues

**Comment by chicagotripp** [comment]
Ok, the second to last option.

**Comment by chicagotripp** [comment]
I cloned your fork, performed a pull on the dmidecode master branch to the latest and greatest commit, performed some merge conflict resolutions, created unified diff files, and then packed them all in to this one zip file. I haven't tested it yet. I accepted all suggestions from AUTHORS (with slight modifications) and dmidecode.c since these were the only 2 issues that required a personal touch.

<img width="602" alt="screen shot 2017-06-15 at 9 10 44 pm" src="https://user-images.githubusercontent.com/8418471/27211023-135dabd2-521c-11e7-91b0-16f958eddc54.png">








[Patches to 3.1.zip](https://github.com/cavaliercoder/dmidecode-osx/files/1079675/Patches.to.3.1.zip)

**Comment by cavaliercoder** [comment]
Thanks for putting some time into. It's really critical that we do test the side-effects of each merge-conflict before proceeding with this.

**Comment by chicagotripp** [comment]
Ok. I had errors during make and I fix them. They work on my system running Mac OS High Sierra version 3. Here is the patch. I'm including the 5 errors as a screenshot.
[dmidecode.c.diff.zip](https://github.com/cavaliercoder/dmidecode-osx/files/1081385/dmidecode.c.diff.zip)
<img width="602" alt="screen shot 2017-06-16 at 11 26 07 am" src="https://user-images.githubusercontent.com/8418471/27235481-9ec73b10-5286-11e7-9064-a22cf72fcc82.png">
<img width="602" alt="screen shot 2017-06-16 at 11 26 36 am" src="https://user-images.githubusercontent.com/8418471/27235506-aee54398-5286-11e7-82f6-153ea6325408.png">

**Comment by cavaliercoder** [comment]
I've rebased onto the `dmidecode-3.1` branch from https://git.savannah.nongnu.org/git/dmidecode.git. Homebrew package upgraded to v3.1.
